# Generated by Django 4.1 on 2022-08-24 08:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('start_day', models.DateField(default=datetime.datetime(2022, 8, 24, 8, 52, 5, 549454, tzinfo=datetime.timezone.utc))),
                ('gender', models.CharField(max_length=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('start_day', models.DateField(default=datetime.datetime(2022, 8, 24, 8, 52, 5, 549454, tzinfo=datetime.timezone.utc))),
                ('gender', models.CharField(max_length=1)),
                ('rate', models.FloatField(default=0.0)),
                ('num_week', models.IntegerField(default=0)),
                ('num_month', models.IntegerField(default=0)),
                ('num_year', models.IntegerField(default=0)),
                ('num_all_trainings', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cardio', 'Cardio'), ('plyo', 'Plyo'), ('upper', 'Upper Body Workout'), ('lower', 'Lower Body Workout'), ('strenght', 'Strenght Training'), ('metcon', 'Full Body Weight Training')], max_length=50)),
                ('duration_min', models.IntegerField(default=60)),
                ('datetime', models.DateTimeField()),
                ('capacity', models.IntegerField(default=15)),
                ('Coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FitUp.coach')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FitUp.client')),
                ('training', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FitUp.training')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2022, 8, 24, 8, 52, 5, 549454, tzinfo=datetime.timezone.utc))),
                ('num_trainings_per_week', models.IntegerField()),
                ('price', models.IntegerField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FitUp.client')),
            ],
        ),
    ]
