# Generated by Django 4.1 on 2022-08-26 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitUp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='rate_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='start_day',
            field=models.DateField(default=datetime.datetime(2022, 8, 26, 16, 12, 57, 905209, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='coach',
            name='start_day',
            field=models.DateField(default=datetime.datetime(2022, 8, 26, 16, 12, 57, 905209, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 26, 16, 12, 57, 905209, tzinfo=datetime.timezone.utc)),
        ),
    ]
