# Generated by Django 4.1 on 2022-08-27 09:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FitUp', '0002_coach_rate_num_alter_client_start_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='start_day',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 9, 16, 20, 182976, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='coach',
            name='start_day',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 9, 16, 20, 182976, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 9, 16, 20, 182976, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='CoachDTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('rate', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
