# Generated by Django 4.1 on 2022-08-27 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitUp', '0004_alter_client_start_day_alter_coach_start_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='enters',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='start_day',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 12, 24, 37, 288493, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='coach',
            name='start_day',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 12, 24, 37, 288493, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 27, 12, 24, 37, 288493, tzinfo=datetime.timezone.utc)),
        ),
    ]
